### ISSUE TITLE
Implement my_malloc size switch case function

### ISSUE THREAD

**Issue by rswhipple** [rswhipple/jsmalloc#33]
DRAFT

we need a function that sorts the memory_allocation request into 1 of 4 size types:
tiny, small, large and huge

if size = tiny :
 - look in t_tiny_chunk ** tiny_chunk_bins for a free_chunk (we still need to create tiny_chunk_bins)
 - if no free_chunk found create_tiny_chunk in correct fpage

**Comment by yogimathius** [comment]
done, will follow this up with additional tickets for unit testing as needed
