### ISSUE TITLE
implement my_free function (returning memory to heap)

### ISSUE THREAD

**Issue by rswhipple** [rswhipple/jsmalloc#4]
## Description
  - Implement the core logic for memory allocation using the chosen allocation strategy.
  - Handle requests for memory allocation of varying sizes and alignment requirements.

## Success Criteria
  - [x] `my_free` correctly de-allocates memory blocks
  - [ ] blocks that are freed are merged with other free memory blocks

**Comment by yogimathius** [comment]
Basic implementation of this is complete in https://github.com/rswhipple/jsmalloc/pull/22. Some work may still need to be done to properly coalesce the blocks?

Closing this ticket for now and will create a new ticket to track that work to be done as it comes up
